sudo: false

language: node_js

node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"

cache:
  directories:
    # cache node modules
    - node_modules

notifications:
  # disable email notification
  email: false

install: npm i -g yarn && yarn global add coveralls && yarn

before_script:
  # use firefox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  # remove unused node modules from cache
  - yarn clean
  # karma tests
  - npm test

after_script:
  # send code-coverage report to coveralls
  - coveralls < ./coverage/lcov.info || true
